// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjdSR44X-h9OV3ueTaSzyb43u7zc6P_cY',
    appId: '1:807746515926:web:9ac9429c5cce8ae9d9ea77',
    messagingSenderId: '807746515926',
    projectId: 'buyandsale-be9e6',
    authDomain: 'buyandsale-be9e6.firebaseapp.com',
    storageBucket: 'buyandsale-be9e6.appspot.com',
    measurementId: 'G-PQHQDEGZD6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApUPAFJn99tMXoVE8UgKn8Cbzny2uN9OQ',
    appId: '1:807746515926:android:cb065d3f92b4c32fd9ea77',
    messagingSenderId: '807746515926',
    projectId: 'buyandsale-be9e6',
    storageBucket: 'buyandsale-be9e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT2M-LePOc0YJPzNU8hpQKT0-5tBItrqg',
    appId: '1:807746515926:ios:cb8dc2ce38c3be23d9ea77',
    messagingSenderId: '807746515926',
    projectId: 'buyandsale-be9e6',
    storageBucket: 'buyandsale-be9e6.appspot.com',
    iosClientId: '807746515926-ldigsfvp31ojrcihgdil2vuc59ih9kh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT2M-LePOc0YJPzNU8hpQKT0-5tBItrqg',
    appId: '1:807746515926:ios:649d148d7025dbf1d9ea77',
    messagingSenderId: '807746515926',
    projectId: 'buyandsale-be9e6',
    storageBucket: 'buyandsale-be9e6.appspot.com',
    iosClientId: '807746515926-d5tircbck7p5ea409jtqqflijfs6um96.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopping.RunnerTests',
  );
}
